/**
 * Créditos de las fotografías de banco con licencia libre y las imágenes ilustrativas generadas con IA usadas en el sitio.
 *
 * Regla: solo licencias que permiten uso comercial y obra derivada (CC BY, CC BY-SA,
 * CC0, dominio público). Cada imagen se recortó y recomprimió; la atribución es
 * obligatoria y se muestra al pie de cada figura.
 *
 * Las fotografías de banco no son activos propios; ninguna imagen se usa como logotipo,
 * favicon ni imagen de marca.
 */

export interface CreditoImagen {
  titulo: string;
  autor: string;
  licencia: string;
  licenciaUrl: string;
  fuente: string;
  alt: string;
  tipo?: 'banco' | 'ia';
}

export const CREDITOS: Record<string, CreditoImagen> = {
  'gen-grado-entry-grade': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Un solo marco de plástico gris con pocas piezas grandes, típico de un kit de nivel inicial.",
    tipo: 'ia',
  },
  'gen-grado-high-grade': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Dos marcos de plástico gris y azul con piezas pequeñas junto a unas pinzas de corte.",
    tipo: 'ia',
  },
  'gen-grado-real-grade': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Marcos de plástico multicolor con piezas diminutas y muy densas junto a una lupa de precisión.",
    tipo: 'ia',
  },
  'gen-grado-master-grade': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Marcos de plástico apilados junto a piezas de armazón interno gris oscuro, sueltas.",
    tipo: 'ia',
  },
  'gen-grado-perfect-grade': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Gran cantidad de marcos de plástico de formato grande con piezas metalizadas, tornillos y un módulo LED.",
    tipo: 'ia',
  },
  'gen-universo-uc': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Colonia espacial cilíndrica en órbita terrestre con la Tierra al fondo.",
    tipo: 'ia',
  },
  'gen-universo-ac': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Grupo de colonias y estaciones orbitales lejanas en un punto de Lagrange, con la Tierra y la Luna.",
    tipo: 'ia',
  },
  'gen-universo-ce': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Laboratorio de biotecnología en órbita con una gran ventana hacia la Tierra.",
    tipo: 'ia',
  },
  'gen-universo-ad': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Elevador orbital que se eleva desde una plataforma oceánica al amanecer.",
    tipo: 'ia',
  },
  'gen-universo-pd': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Asentamiento industrial desgastado en la superficie de Marte con tormentas de polvo.",
    tipo: 'ia',
  },
  'gen-universo-as': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Campus corporativo moderno dentro de una estación orbital, arquitectura blanca y luminosa.",
    tipo: 'ia',
  },
  'gen-universo-cc': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Campo nocturno bajo una Luna llena enorme con ruinas antiguas cubiertas de vegetación.",
    tipo: 'ia',
  },
  'gen-art-que-es-un-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Marcos de plástico sin cortar junto a un instructivo con diagramas de piezas.",
    tipo: 'ia',
  },
  'gen-art-como-armar-tu-primer-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Manos separando una pieza de plástico del marco con pinzas de corte.",
    tipo: 'ia',
  },
  'gen-art-herramientas-para-armar-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Herramientas de modelismo ordenadas sobre un tapete de corte.",
    tipo: 'ia',
  },
  'gen-art-panel-lining-topcoat-acabados': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Rotulador de punta fina marcando líneas de panel en una pieza de plástico blanca.",
    tipo: 'ia',
  },
  'gen-art-por-que-amarillean-los-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Dos piezas de plástico idénticas: una blanca y otra amarillenta por el tiempo.",
    tipo: 'ia',
  },
  'gen-art-grados-de-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Cinco marcos de plástico ordenados de menor a mayor densidad de piezas.",
    tipo: 'ia',
  },
  'gen-art-master-grade-vs-real-grade': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Dos pilas de marcos de plástico comparadas con una regla metálica.",
    tipo: 'ia',
  },
  'gen-art-perfect-grade-que-es': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Caja grande y lisa llena de marcos de plástico empacados.",
    tipo: 'ia',
  },
  'gen-art-glosario-gunpla-terminos': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Cuaderno abierto con pluma y piezas de plástico sueltas.",
    tipo: 'ia',
  },
  'gen-art-que-significa-ver-ka': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Macro de una pieza de plástico con detalle grabado muy fino.",
    tipo: 'ia',
  },
  'gen-art-checklist-antes-de-comprar-tu-primer-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Cajas lisas de kits junto a una tabla con una lista de verificación en blanco.",
    tipo: 'ia',
  },
  'gen-art-gundam-armable-cual-comprar': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Tres cajas lisas de distinto tamaño en fila.",
    tipo: 'ia',
  },
  'gen-art-como-fotografiar-tu-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Estudio fotográfico de mesa con cámara, caja de luz y una pieza sobre base giratoria.",
    tipo: 'ia',
  },
  'gen-art-comprar-vender-gunpla-segunda-mano': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Dos personas revisan el contenido de una caja de kit sobre una mesa.",
    tipo: 'ia',
  },
  'gen-art-importar-gunpla-a-mexico': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Paquete internacional con sobre de documentos aduanales sobre un escritorio.",
    tipo: 'ia',
  },
  'gen-art-preventas-y-p-bandai-desde-mexico': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Escritorio con laptop, calendario con una fecha marcada y un paquete.",
    tipo: 'ia',
  },
  'gen-art-gunpla-fuera-de-cdmx': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Paquetes listos para envío en la trastienda de una tienda de hobby.",
    tipo: 'ia',
  },
  'gen-art-comunidad-gundam-mexico-como-unirte': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Mesa compartida donde varias personas arman modelos juntas.",
    tipo: 'ia',
  },
  'gen-art-eventos-gundam-mexico': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Sala de exhibición de modelismo con mesas de modelos a escala.",
    tipo: 'ia',
  },
  'gen-art-gundam-card-game-en-mexico': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Manos de dos jugadores sobre un tapete con cartas boca abajo en un torneo.",
    tipo: 'ia',
  },
  'gen-art-videojuegos-de-gundam-que-puedes-jugar-hoy': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Manos con un control de videojuego iluminadas por la pantalla.",
    tipo: 'ia',
  },
  'gen-art-gundam-assemble-que-es': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Mesa de juego estratégico con escenografía, dados y cinta métrica.",
    tipo: 'ia',
  },
  'gen-art-requiem-for-vengeance-que-es': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Estación de trabajo de animación 3D con un paisaje renderizado en tiempo real.",
    tipo: 'ia',
  },
  'gen-art-gundam-live-action-netflix': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Cámara de cine en un set de filmación con pantalla verde.",
    tipo: 'ia',
  },
  'gen-art-cual-gundam-ver-primero': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Sala acogedora de noche iluminada por el brillo de la televisión.",
    tipo: 'ia',
  },
  'art-donde-ver': {
    titulo: 'Gundam figure at Don Quijote Kaheka',
    autor: 'jdnx',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/21442511@N08/52194570136',
    alt: 'Model kit expuesto en el mostrador de una tienda de hobby.',
  },
  'art-gundam-wing': {
    titulo: 'Wing Zero Kai',
    autor: 'joo0ey',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/37238219@N00/5066980320',
    alt: 'Primer plano de un model kit del Wing Gundam Zero Kai.',
  },
  'art-historia-mexico': {
    titulo: 'GUNDAM!',
    autor: 'joo0ey',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/37238219@N00/3247856863',
    alt: 'Primer plano de un model kit del RX-78-2.',
  },
  'art-orden': {
    titulo: 'BANDAI GUNPLA',
    autor: 'othree',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/12452841@N00/9486175112',
    alt: 'Varios model kits de distintas series expuestos juntos en una vitrina.',
  },
  'art-universal-century': {
    titulo: 'RX-0 Unicorn Gundam (Unicorn Mode)',
    autor: 'Nelo Hotsuma',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/63122283@N06/44100055452',
    alt: 'Model kit del RX-0 Unicorn Gundam en modo unicornio.',
  },
  'gui-donde-comprar': {
    titulo: 'The Gundam Base Tokyo, entrance',
    autor: 'Syced',
    licencia: 'CC0 1.0',
    licenciaUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    fuente: 'https://commons.wikimedia.org/w/index.php?curid=129634893',
    alt: 'Entrada de la tienda The Gundam Base en Tokio.',
  },
  'gui-original': {
    titulo: 'BANDAI GUNPLA RG',
    autor: 'othree',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/12452841@N00/9486171428',
    alt: 'Model kit Real Grade del RX-78-2 expuesto en una vitrina.',
  },
  'gui-precio': {
    titulo: 'BANDAI GUNPLA',
    autor: 'othree',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/12452841@N00/9486179884',
    alt: 'Model kits High Grade expuestos junto a su ficha de precio.',
  },
  'hub-articulos': {
    titulo: 'Airfix Islander pieces & travelling work space, annotated, at the registration table, the day before the contest.',
    autor: 'wbaiv',
    licencia: 'CC BY-SA 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    fuente: 'https://www.flickr.com/photos/9998127@N06/4900843278',
    alt: 'Mesa de trabajo de modelismo con pinturas, piezas y herramientas.',
  },
  'hub-comunidad': {
    titulo: 'Frederic Duch 3D Model1',
    autor: 'Jefferson Lab',
    licencia: 'Dominio público (PDM 1.0)',
    licenciaUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    fuente: 'https://www.flickr.com/photos/53950384@N02/54719199815',
    alt: 'Dos personas armando un diorama a escala en una mesa de taller.',
  },
  'hub-eventos': {
    titulo: 'GUNPLA EXPO 鋼彈模型博覽會 – TAIWAN 2013',
    autor: 'othree',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/12452841@N00/9483342649',
    alt: 'Primer plano de un model kit expuesto en una exposición de Gunpla.',
  },
  'hub-guias': {
    titulo: 'Clippers, tweezers, scissors, sanding sticks',
    autor: 'wbaiv',
    licencia: 'CC BY-SA 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    fuente: 'https://www.flickr.com/photos/9998127@N06/4569806198',
    alt: 'Herramientas de modelismo sobre una mesa: pinzas, tijeras, limas, cúter y pinturas.',
  },
  'hub-gunpla': {
    titulo: 'Pull the plastic out of the bags',
    autor: 'Kaeru',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/51035756584@N01/48588655',
    alt: 'Runners de plástico de un model kit recién sacados de la bolsa, junto al instructivo.',
  },
  'hub-kits': {
    titulo: 'One or two Gundam models',
    autor: 'DocChewbacca',
    licencia: 'CC BY-SA 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    fuente: 'https://www.flickr.com/photos/49462908@N00/2871304398',
    alt: 'Estantería de tienda llena de cajas de model kits de Gunpla.',
  },
  'hub-mobile-suits': {
    titulo: 'MG MSA-0011(Ext) Ex-S Gundam',
    autor: 'Mathias Appel',
    licencia: 'CC0 1.0',
    licenciaUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    fuente: 'https://www.flickr.com/photos/91501748@N07/8566837608',
    alt: 'Model kit Master Grade del Ex-S Gundam fotografiado sobre fondo negro.',
  },
  'hub-noticias': {
    titulo: 'MG MSN-001A1 Delta Plus',
    autor: 'Mathias Appel',
    licencia: 'CC0 1.0',
    licenciaUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    fuente: 'https://www.flickr.com/photos/91501748@N07/8566832944',
    alt: 'Model kit Master Grade del Delta Plus fotografiado sobre fondo negro.',
  },
  'hub-personajes': {
    titulo: 'Singapore Gundam Model Kit Challenge 2008 - Hallelujah Rescue Campaign',
    autor: 'animaster',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/19043905@N06/3037571181',
    alt: 'Diorama con dos model kits en una escena de combate sobre ruinas.',
  },
  'hub-series': {
    titulo: 'BANDAI GUNPLA HG',
    autor: 'othree',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/12452841@N00/9486180634',
    alt: 'Vitrina con varios model kits de la línea High Grade expuestos.',
  },
  'hub-tiendas': {
    titulo: 'Gundam Model Kit Challenge - Takashimaya Singapore',
    autor: 'animaster',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/19043905@N06/3045931836',
    alt: 'Interior de una tienda de hobby con vitrinas de model kits.',
  },
  'hub-universos': {
    titulo: 'Causeway Bay Gundam EXPO Event',
    autor: 'Marco Hazard',
    licencia: 'CC BY-SA 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    fuente: 'https://www.flickr.com/photos/42405591@N02/20817729638',
    alt: 'Estatua a escala real del RX-0 Unicorn Gundam instalada en la vía pública.',
  },
  'ms-exia': {
    titulo: 'GUNDAM EXIA (REAL GRADE KIT)',
    autor: 'fotowesley',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/48923585@N06/14238127994',
    alt: 'Model kit Real Grade del GN-001 Gundam Exia.',
  },
  'ms-nu': {
    titulo: 'Nu Gundam',
    autor: 'tsuihin - TimoStudios',
    licencia: 'CC BY-SA 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    fuente: 'https://www.flickr.com/photos/19136074@N06/3118122178',
    alt: 'Model kit del RX-93 Nu Gundam armado.',
  },
  'ms-sazabi': {
    titulo: 'Sazabi',
    autor: 'othree',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/12452841@N00/14981199119',
    alt: 'Model kit del MSN-04 Sazabi armado.',
  },
  'ms-wing': {
    titulo: 'Wing GUNDAM',
    autor: 'othree',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/12452841@N00/14981296288',
    alt: 'Model kit del XXXG-01W Wing Gundam armado.',
  },
  'ms-zaku-ii': {
    titulo: 'MS-06S Zaku II',
    autor: 'JohnWCoke',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/86371376@N05/7912612886',
    alt: 'Model kit del MS-06S Zaku II armado.',
  },
  'ms-zeta': {
    titulo: 'Zeta Elevates',
    autor: 'JohnWCoke',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/86371376@N05/8001402471',
    alt: 'Model kit del MSZ-006 Zeta Gundam armado.',
  },
};
