/**
 * Créditos de las fotografías de banco con licencia libre y las imágenes ilustrativas generadas con IA usadas en el sitio.
 *
 * Regla: solo licencias que permiten uso comercial y obra derivada (CC BY, CC BY-SA,
 * CC0, dominio público). Cada imagen se recortó y recomprimió; la atribución es
 * obligatoria y se muestra al pie de cada figura.
 *
 * Las fotografías de banco no son activos propios; ninguna imagen se usa como logotipo,
 * favicon ni imagen de marca.
 */

export interface CreditoImagen {
  titulo: string;
  autor: string;
  licencia: string;
  licenciaUrl: string;
  fuente: string;
  alt: string;
  tipo?: 'banco' | 'ia';
}

export const CREDITOS: Record<string, CreditoImagen> = {
  'gen-grado-entry-grade': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Un solo marco de plástico gris con pocas piezas grandes, típico de un kit de nivel inicial.",
    tipo: 'ia',
  },
  'gen-grado-high-grade': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Dos marcos de plástico gris y azul con piezas pequeñas junto a unas pinzas de corte.",
    tipo: 'ia',
  },
  'gen-grado-real-grade': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Marcos de plástico multicolor con piezas diminutas y muy densas junto a una lupa de precisión.",
    tipo: 'ia',
  },
  'gen-grado-master-grade': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Marcos de plástico apilados junto a piezas de armazón interno gris oscuro, sueltas.",
    tipo: 'ia',
  },
  'gen-grado-perfect-grade': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Gran cantidad de marcos de plástico de formato grande con piezas metalizadas, tornillos y un módulo LED.",
    tipo: 'ia',
  },
  'gen-universo-uc': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Colonia espacial cilíndrica en órbita terrestre con la Tierra al fondo.",
    tipo: 'ia',
  },
  'gen-universo-ac': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Grupo de colonias y estaciones orbitales lejanas en un punto de Lagrange, con la Tierra y la Luna.",
    tipo: 'ia',
  },
  'gen-universo-ce': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Laboratorio de biotecnología en órbita con una gran ventana hacia la Tierra.",
    tipo: 'ia',
  },
  'gen-universo-ad': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Elevador orbital que se eleva desde una plataforma oceánica al amanecer.",
    tipo: 'ia',
  },
  'gen-universo-pd': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Asentamiento industrial desgastado en la superficie de Marte con tormentas de polvo.",
    tipo: 'ia',
  },
  'gen-universo-as': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Campus corporativo moderno dentro de una estación orbital, arquitectura blanca y luminosa.",
    tipo: 'ia',
  },
  'gen-universo-cc': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Campo nocturno bajo una Luna llena enorme con ruinas antiguas cubiertas de vegetación.",
    tipo: 'ia',
  },
  'gen-art-que-es-un-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Marcos de plástico sin cortar junto a un instructivo con diagramas de piezas.",
    tipo: 'ia',
  },
  'gen-art-como-armar-tu-primer-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Manos separando una pieza de plástico del marco con pinzas de corte.",
    tipo: 'ia',
  },
  'gen-art-herramientas-para-armar-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Herramientas de modelismo ordenadas sobre un tapete de corte.",
    tipo: 'ia',
  },
  'gen-art-panel-lining-topcoat-acabados': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Rotulador de punta fina marcando líneas de panel en una pieza de plástico blanca.",
    tipo: 'ia',
  },
  'gen-art-por-que-amarillean-los-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Dos piezas de plástico idénticas: una blanca y otra amarillenta por el tiempo.",
    tipo: 'ia',
  },
  'gen-art-grados-de-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Cinco marcos de plástico ordenados de menor a mayor densidad de piezas.",
    tipo: 'ia',
  },
  'gen-art-master-grade-vs-real-grade': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Dos pilas de marcos de plástico comparadas con una regla metálica.",
    tipo: 'ia',
  },
  'gen-art-perfect-grade-que-es': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Caja grande y lisa llena de marcos de plástico empacados.",
    tipo: 'ia',
  },
  'gen-art-glosario-gunpla-terminos': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Cuaderno abierto con pluma y piezas de plástico sueltas.",
    tipo: 'ia',
  },
  'gen-art-que-significa-ver-ka': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Macro de una pieza de plástico con detalle grabado muy fino.",
    tipo: 'ia',
  },
  'gen-art-checklist-antes-de-comprar-tu-primer-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Cajas lisas de kits junto a una tabla con una lista de verificación en blanco.",
    tipo: 'ia',
  },
  'gen-art-gundam-armable-cual-comprar': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Tres cajas lisas de distinto tamaño en fila.",
    tipo: 'ia',
  },
  'gen-art-como-fotografiar-tu-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Estudio fotográfico de mesa con cámara, caja de luz y una pieza sobre base giratoria.",
    tipo: 'ia',
  },
  'gen-art-comprar-vender-gunpla-segunda-mano': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Dos personas revisan el contenido de una caja de kit sobre una mesa.",
    tipo: 'ia',
  },
  'gen-art-importar-gunpla-a-mexico': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Paquete internacional con sobre de documentos aduanales sobre un escritorio.",
    tipo: 'ia',
  },
  'gen-art-preventas-y-p-bandai-desde-mexico': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Escritorio con laptop, calendario con una fecha marcada y un paquete.",
    tipo: 'ia',
  },
  'gen-art-gunpla-fuera-de-cdmx': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Paquetes listos para envío en la trastienda de una tienda de hobby.",
    tipo: 'ia',
  },
  'gen-art-comunidad-gundam-mexico-como-unirte': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Mesa compartida donde varias personas arman modelos juntas.",
    tipo: 'ia',
  },
  'gen-art-eventos-gundam-mexico': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Sala de exhibición de modelismo con mesas de modelos a escala.",
    tipo: 'ia',
  },
  'gen-art-gundam-card-game-en-mexico': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Manos de dos jugadores sobre un tapete con cartas boca abajo en un torneo.",
    tipo: 'ia',
  },
  'gen-art-videojuegos-de-gundam-que-puedes-jugar-hoy': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Manos con un control de videojuego iluminadas por la pantalla.",
    tipo: 'ia',
  },
  'gen-art-gundam-assemble-que-es': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Mesa de juego estratégico con escenografía, dados y cinta métrica.",
    tipo: 'ia',
  },
  'gen-art-requiem-for-vengeance-que-es': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Estación de trabajo de animación 3D con un paisaje renderizado en tiempo real.",
    tipo: 'ia',
  },
  'gen-art-gundam-live-action-netflix': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Cámara de cine en un set de filmación con pantalla verde.",
    tipo: 'ia',
  },
  'gen-art-cual-gundam-ver-primero': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Sala acogedora de noche iluminada por el brillo de la televisión.",
    tipo: 'ia',
  },
  'gen-ser-08th-ms-team': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Selva del sudeste asiático con niebla y un campamento improvisado junto a un río.",
    tipo: 'ia',
  },
  'gen-ser-gquuuuuux': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Calle nocturna con luces de neón dentro de una colonia espacial cilíndrica.",
    tipo: 'ia',
  },
  'gen-ser-gundam-f91': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Barrio residencial dentro de una colonia espacial al atardecer, con humo a lo lejos.",
    tipo: 'ia',
  },
  'gen-ser-gundam-seed-destiny': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Costa en llamas al atardecer con una ciudad isleña a lo lejos.",
    tipo: 'ia',
  },
  'gen-ser-gundam-seed-freedom': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Panorama de espacio profundo con una nebulosa luminosa y restos brillantes.",
    tipo: 'ia',
  },
  'gen-ser-gundam-seed': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Astillero industrial oculto dentro de un asteroide.",
    tipo: 'ia',
  },
  'gen-ser-iron-blooded-orphans': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Base industrial oxidada en el desierto de Marte.",
    tipo: 'ia',
  },
  'gen-ser-mobile-suit-gundam-hathaway': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Ciudad costera tropical de noche bajo lluvia intensa.",
    tipo: 'ia',
  },
  'gen-ser-mobile-suit-gundam-thunderbolt': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Campo de restos de colonias destruidas iluminado por descargas eléctricas.",
    tipo: 'ia',
  },
  'gen-ser-requiem-for-vengeance': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Pueblo europeo en ruinas cubierto de nieve al anochecer.",
    tipo: 'ia',
  },
  'gen-ser-the-witch-from-mercury': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Horizonte de Mercurio con el Sol enorme y una estación orbital blanca.",
    tipo: 'ia',
  },
  'gen-ser-turn-a-gundam': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Aldea junto a un lago bajo una Luna llena enorme, con una estructura antigua en la colina.",
    tipo: 'ia',
  },
  'gen-ms-asw-g-08-gundam-barbatos': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Hangar industrial oxidado en Marte con una grúa de mantenimiento vacía.",
    tipo: 'ia',
  },
  'gen-ms-asw-g-08-gundam-barbatos-lupus-rex': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Cañón marciano al anochecer con restos metálicos y una tormenta de polvo.",
    tipo: 'ia',
  },
  'gen-ms-f91-gundam-f91': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Casco exterior de una colonia espacial con destellos a lo lejos.",
    tipo: 'ia',
  },
  'gen-ms-gat-x105-strike-gundam': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Fábrica secreta dentro de una colonia con luces de emergencia rojas.",
    tipo: 'ia',
  },
  'gen-ms-gms-alpha-red-gundam': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Deshuesadero de colonia de noche bañado en luz roja.",
    tipo: 'ia',
  },
  'gen-ms-gms-omega-gquuuuuux': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Arena subterránea iluminada con reflectores azules y magenta.",
    tipo: 'ia',
  },
  'gen-ms-gn-002-gundam-dynames': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Acantilado sobre un desierto al amanecer con una línea de visión despejada.",
    tipo: 'ia',
  },
  'gen-ms-gn-003-gundam-kyrios': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Estelas de alta velocidad entre nubes sobre el océano.",
    tipo: 'ia',
  },
  'gen-ms-gn-005-gundam-virtue': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Maquinaria industrial pesada con ventilas incandescentes en una fundición.",
    tipo: 'ia',
  },
  'gen-ms-mbf-p02-gundam-astray-red-frame': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Chatarrería orbital con restos flotantes y un remolcador pequeño.",
    tipo: 'ia',
  },
  'gen-ms-mighty-strike-freedom-gundam': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Estallido de luz dorada en el espacio profundo.",
    tipo: 'ia',
  },
  'gen-ms-mrx-009-psycho-gundam': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Megaciudad asiática de noche bajo tormenta, con reflectores en el cielo.",
    tipo: 'ia',
  },
  'gen-ms-ms-06rb-zaku-ii-solari': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Bosque europeo nevado en invierno con un resplandor lejano.",
    tipo: 'ia',
  },
  'gen-ms-nz-666-kshatriya': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Interior rocoso de una base militar en un asteroide.",
    tipo: 'ia',
  },
  'gen-ms-oz-13ms-gundam-epyon': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Planicie antártica de noche bajo la Luna, con nieve arrastrada por el viento.",
    tipo: 'ia',
  },
  'gen-ms-rx-104ff-penelope': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Frente de tormenta con relámpagos acercándose a una costa tropical.",
    tipo: 'ia',
  },
  'gen-ms-rx-105-xi-gundam': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Tormenta eléctrica nocturna sobre un mar tropical.",
    tipo: 'ia',
  },
  'gen-ms-rx-78al-atlas-gundam': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Isla selvática del Pacífico al amanecer con vapor sobre el río.",
    tipo: 'ia',
  },
  'gen-ms-rx-78ge-gundam-ex': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Paso de montaña nevado en Europa con un puente de piedra en ruinas.",
    tipo: 'ia',
  },
  'gen-ms-rx-79g-ez8': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Claro de selva con un taller de campaña improvisado bajo la lluvia.",
    tipo: 'ia',
  },
  'gen-ms-system-a99-turn-a-gundam': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Estructura antigua emergiendo de una montaña bajo la luz de la Luna.",
    tipo: 'ia',
  },
  'gen-ms-x-ex01-gundam-calibarn': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Estructura orbital blanca atravesada por un solo haz de luz.",
    tipo: 'ia',
  },
  'gen-ms-xm-07-vigna-ghina': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Interior barroco aristocrático con rosas rojas dentro de una colonia.",
    tipo: 'ia',
  },
  'gen-ms-xvx-016-gundam-aerial': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Arena blanca de duelos dentro de una academia orbital.",
    tipo: 'ia',
  },
  'gen-ms-xxxg-00w0-wing-gundam-zero': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Campo de hielo antártico bajo una aurora verde.",
    tipo: 'ia',
  },
  'gen-ms-xxxg-01d-gundam-deathscythe': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Campanario de iglesia de piedra de noche bajo una luna creciente.",
    tipo: 'ia',
  },
  'gen-ms-zgmf-x10a-freedom-gundam': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Espacio profundo con una fuente de luz azul y estelas dispersas.",
    tipo: 'ia',
  },
  'gen-ms-zgmf-x20a-strike-freedom-gundam': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Puente de mando de una nave espacial con ventanal hacia las estrellas.",
    tipo: 'ia',
  },
  'gen-ms-zgmf-x42s-destiny-gundam': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Cielo en llamas al atardecer sobre el océano.",
    tipo: 'ia',
  },
  'gen-per-allelujah-haptism': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Asiento de piloto vacío iluminado mitad naranja y mitad azul.",
    tipo: 'ia',
  },
  'gen-per-amate-yuzuriha': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Azotea nocturna con vista a luces de neón y una mochila escolar.",
    tipo: 'ia',
  },
  'gen-per-amuro-ray': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Mesa de trabajo de electrónica con circuitos y cautín.",
    tipo: 'ia',
  },
  'gen-per-banagher-links': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Ventana de dormitorio con vista a un puerto industrial de colonia.",
    tipo: 'ia',
  },
  'gen-per-cecily-fairchild': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Mostrador de panadería familiar con pan recién hecho.",
    tipo: 'ia',
  },
  'gen-per-char-aznable': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Estela roja como un cometa cruzando un campo de estrellas.",
    tipo: 'ia',
  },
  'gen-per-duo-maxwell': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Iglesia de piedra al anochecer con velas encendidas.",
    tipo: 'ia',
  },
  'gen-per-four-murasame': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Calle nocturna mojada con reflejos de neón.",
    tipo: 'ia',
  },
  'gen-per-hathaway-noa': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Balcón de hotel tropical al atardecer con vista al mar.",
    tipo: 'ia',
  },
  'gen-per-heero-yuy': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Mar tranquilo al amanecer con una línea de luz en el horizonte.",
    tipo: 'ia',
  },
  'gen-per-io-fleming': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Disco de vinil girando en un tocadiscos con luz tenue.",
    tipo: 'ia',
  },
  'gen-per-iria-solari': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Bosque invernal nevado al anochecer con huellas solitarias.",
    tipo: 'ia',
  },
  'gen-per-kamille-bidan': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Planeador de aeromodelismo sobre el pasto dentro de una colonia.",
    tipo: 'ia',
  },
  'gen-per-kira-yamato': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Playa tropical al atardecer con una laptop cerrada en la arena.",
    tipo: 'ia',
  },
  'gen-per-lacus-clyne': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Escenario vacío con un micrófono bajo una luz rosa suave.",
    tipo: 'ia',
  },
  'gen-per-lockon-stratos': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Calle de un pueblo irlandés bajo la lluvia.",
    tipo: 'ia',
  },
  'gen-per-loran-cehack': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Mansión campestre junto a un lago bajo una Luna llena enorme.",
    tipo: 'ia',
  },
  'gen-per-lowe-guele': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Taller de chatarrero en órbita con herramientas y una escotilla hacia la Tierra.",
    tipo: 'ia',
  },
  'gen-per-marida-cruz': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Pasillo estrecho de una nave militar con una litera y luz verde.",
    tipo: 'ia',
  },
  'gen-per-mikazuki-augus': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Roca en el desierto marciano con una bolsa de frutos secos.",
    tipo: 'ia',
  },
  'gen-per-seabook-arno': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Patio escolar en una colonia durante un festival nocturno.",
    tipo: 'ia',
  },
  'gen-per-setsuna-f-seiei': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Aldea desértica devastada al anochecer.",
    tipo: 'ia',
  },
  'gen-per-shinn-asuka': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Bosque quemado en la costa de una isla al amanecer.",
    tipo: 'ia',
  },
  'gen-per-shiro-amada': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Puente sobre un río selvático entre niebla.",
    tipo: 'ia',
  },
  'gen-per-suletta-mercury': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Invernadero con plantas de jitomate dentro de una estación espacial.",
    tipo: 'ia',
  },
  'gen-per-tieria-erde': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Centro de datos blanco con servidores iluminados en violeta.",
    tipo: 'ia',
  },
  'gen-art-char-aznable-quien-es': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Pasillo de nave espacial bañado en luz roja.",
    tipo: 'ia',
  },
  'gen-art-cronologia-de-gundam-explicada': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Estelas de estrellas sobre un observatorio de montaña.",
    tipo: 'ia',
  },
  'gen-art-el-zaku-por-que-importa': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Línea de producción con filas de piezas idénticas.",
    tipo: 'ia',
  },
  'gen-art-en-que-orden-ver-gundam-wing': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Pila de videocasetes sin etiqueta junto a un televisor antiguo.",
    tipo: 'ia',
  },
  'gen-art-existe-lego-gundam': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Bloques de construcción genéricos junto a un marco de plástico.",
    tipo: 'ia',
  },
  'gen-art-figuras-de-gundam-vs-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Repisa de coleccionista con una vitrina de acrílico vacía y una caja lisa.",
    tipo: 'ia',
  },
  'gen-art-gundam-build-fighters-que-es': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Mesa de competencia de modelismo bajo un reflector.",
    tipo: 'ia',
  },
  'gen-art-gundam-escala-real-yokohama-odaiba': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Puerto japonés a la hora azul con luces reflejadas en la bahía.",
    tipo: 'ia',
  },
  'gen-art-gundam-hathaway-2-sorcery-of-nymph-circe': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Ciudad tropical del sudeste asiático al atardecer después de la lluvia.",
    tipo: 'ia',
  },
  'gen-art-gundam-rogue-orbit-todo-lo-que-se-sabe': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Monitor curvo con una nebulosa en una habitación oscura de videojuegos.",
    tipo: 'ia',
  },
  'gen-art-gundam-seed-guia-y-orden': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Costa de una nación isleña al atardecer con una ciudad portuaria.",
    tipo: 'ia',
  },
  'gen-art-gundam-unicorn-guia': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Tapiz medieval de un unicornio en la sala de un museo.",
    tipo: 'ia',
  },
  'gen-art-pilotos-de-gundam-wing': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Cinco estelas como meteoros entrando a la atmósfera terrestre.",
    tipo: 'ia',
  },
  'gen-art-que-es-gundam': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "La Tierra desde la órbita con colonias espaciales a lo lejos.",
    tipo: 'ia',
  },
  'gen-art-que-significa-gundam': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Mesa de diseñador industrial con bocetos de formas geométricas.",
    tipo: 'ia',
  },
  'gen-art-the-gundam-base-mexico': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Paseo de la Reforma en la Ciudad de México a la hora azul.",
    tipo: 'ia',
  },
  'gen-art-witch-from-mercury-guia': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "El Sol saliendo sobre el horizonte de Mercurio.",
    tipo: 'ia',
  },
  'gen-art-zeta-gundam-guia': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Interior oscuro de una colonia espacial dañada con restos flotando.",
    tipo: 'ia',
  },
  'art-donde-ver': {
    titulo: 'Gundam figure at Don Quijote Kaheka',
    autor: 'jdnx',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/21442511@N08/52194570136',
    alt: 'Model kit expuesto en el mostrador de una tienda de hobby.',
  },
  'art-gundam-wing': {
    titulo: 'Wing Zero Kai',
    autor: 'joo0ey',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/37238219@N00/5066980320',
    alt: 'Primer plano de un model kit del Wing Gundam Zero Kai.',
  },
  'art-historia-mexico': {
    titulo: 'GUNDAM!',
    autor: 'joo0ey',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/37238219@N00/3247856863',
    alt: 'Primer plano de un model kit del RX-78-2.',
  },
  'art-orden': {
    titulo: 'BANDAI GUNPLA',
    autor: 'othree',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/12452841@N00/9486175112',
    alt: 'Varios model kits de distintas series expuestos juntos en una vitrina.',
  },
  'art-universal-century': {
    titulo: 'RX-0 Unicorn Gundam (Unicorn Mode)',
    autor: 'Nelo Hotsuma',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/63122283@N06/44100055452',
    alt: 'Model kit del RX-0 Unicorn Gundam en modo unicornio.',
  },
  'gui-donde-comprar': {
    titulo: 'The Gundam Base Tokyo, entrance',
    autor: 'Syced',
    licencia: 'CC0 1.0',
    licenciaUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    fuente: 'https://commons.wikimedia.org/w/index.php?curid=129634893',
    alt: 'Entrada de la tienda The Gundam Base en Tokio.',
  },
  'gui-original': {
    titulo: 'BANDAI GUNPLA RG',
    autor: 'othree',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/12452841@N00/9486171428',
    alt: 'Model kit Real Grade del RX-78-2 expuesto en una vitrina.',
  },
  'gui-precio': {
    titulo: 'BANDAI GUNPLA',
    autor: 'othree',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/12452841@N00/9486179884',
    alt: 'Model kits High Grade expuestos junto a su ficha de precio.',
  },
  'hub-articulos': {
    titulo: 'Airfix Islander pieces & travelling work space, annotated, at the registration table, the day before the contest.',
    autor: 'wbaiv',
    licencia: 'CC BY-SA 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    fuente: 'https://www.flickr.com/photos/9998127@N06/4900843278',
    alt: 'Mesa de trabajo de modelismo con pinturas, piezas y herramientas.',
  },
  'hub-comunidad': {
    titulo: 'Frederic Duch 3D Model1',
    autor: 'Jefferson Lab',
    licencia: 'Dominio público (PDM 1.0)',
    licenciaUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    fuente: 'https://www.flickr.com/photos/53950384@N02/54719199815',
    alt: 'Dos personas armando un diorama a escala en una mesa de taller.',
  },
  'hub-eventos': {
    titulo: 'GUNPLA EXPO 鋼彈模型博覽會 – TAIWAN 2013',
    autor: 'othree',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/12452841@N00/9483342649',
    alt: 'Primer plano de un model kit expuesto en una exposición de Gunpla.',
  },
  'hub-guias': {
    titulo: 'Clippers, tweezers, scissors, sanding sticks',
    autor: 'wbaiv',
    licencia: 'CC BY-SA 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    fuente: 'https://www.flickr.com/photos/9998127@N06/4569806198',
    alt: 'Herramientas de modelismo sobre una mesa: pinzas, tijeras, limas, cúter y pinturas.',
  },
  'hub-gunpla': {
    titulo: 'Pull the plastic out of the bags',
    autor: 'Kaeru',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/51035756584@N01/48588655',
    alt: 'Runners de plástico de un model kit recién sacados de la bolsa, junto al instructivo.',
  },
  'hub-kits': {
    titulo: 'One or two Gundam models',
    autor: 'DocChewbacca',
    licencia: 'CC BY-SA 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    fuente: 'https://www.flickr.com/photos/49462908@N00/2871304398',
    alt: 'Estantería de tienda llena de cajas de model kits de Gunpla.',
  },
  'hub-mobile-suits': {
    titulo: 'MG MSA-0011(Ext) Ex-S Gundam',
    autor: 'Mathias Appel',
    licencia: 'CC0 1.0',
    licenciaUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    fuente: 'https://www.flickr.com/photos/91501748@N07/8566837608',
    alt: 'Model kit Master Grade del Ex-S Gundam fotografiado sobre fondo negro.',
  },
  'hub-noticias': {
    titulo: 'MG MSN-001A1 Delta Plus',
    autor: 'Mathias Appel',
    licencia: 'CC0 1.0',
    licenciaUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    fuente: 'https://www.flickr.com/photos/91501748@N07/8566832944',
    alt: 'Model kit Master Grade del Delta Plus fotografiado sobre fondo negro.',
  },
  'hub-personajes': {
    titulo: 'Singapore Gundam Model Kit Challenge 2008 - Hallelujah Rescue Campaign',
    autor: 'animaster',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/19043905@N06/3037571181',
    alt: 'Diorama con dos model kits en una escena de combate sobre ruinas.',
  },
  'hub-series': {
    titulo: 'BANDAI GUNPLA HG',
    autor: 'othree',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/12452841@N00/9486180634',
    alt: 'Vitrina con varios model kits de la línea High Grade expuestos.',
  },
  'hub-tiendas': {
    titulo: 'Gundam Model Kit Challenge - Takashimaya Singapore',
    autor: 'animaster',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/19043905@N06/3045931836',
    alt: 'Interior de una tienda de hobby con vitrinas de model kits.',
  },
  'hub-universos': {
    titulo: 'Causeway Bay Gundam EXPO Event',
    autor: 'Marco Hazard',
    licencia: 'CC BY-SA 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    fuente: 'https://www.flickr.com/photos/42405591@N02/20817729638',
    alt: 'Estatua a escala real del RX-0 Unicorn Gundam instalada en la vía pública.',
  },
  'ms-exia': {
    titulo: 'GUNDAM EXIA (REAL GRADE KIT)',
    autor: 'fotowesley',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/48923585@N06/14238127994',
    alt: 'Model kit Real Grade del GN-001 Gundam Exia.',
  },
  'ms-nu': {
    titulo: 'Nu Gundam',
    autor: 'tsuihin - TimoStudios',
    licencia: 'CC BY-SA 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    fuente: 'https://www.flickr.com/photos/19136074@N06/3118122178',
    alt: 'Model kit del RX-93 Nu Gundam armado.',
  },
  'ms-sazabi': {
    titulo: 'Sazabi',
    autor: 'othree',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/12452841@N00/14981199119',
    alt: 'Model kit del MSN-04 Sazabi armado.',
  },
  'ms-wing': {
    titulo: 'Wing GUNDAM',
    autor: 'othree',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/12452841@N00/14981296288',
    alt: 'Model kit del XXXG-01W Wing Gundam armado.',
  },
  'ms-zaku-ii': {
    titulo: 'MS-06S Zaku II',
    autor: 'JohnWCoke',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/86371376@N05/7912612886',
    alt: 'Model kit del MS-06S Zaku II armado.',
  },
  'ms-zeta': {
    titulo: 'Zeta Elevates',
    autor: 'JohnWCoke',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/86371376@N05/8001402471',
    alt: 'Model kit del MSZ-006 Zeta Gundam armado.',
  },
};
