/**
 * Créditos de las fotografías de banco con licencia libre y las imágenes ilustrativas generadas con IA usadas en el sitio.
 *
 * Regla: solo licencias que permiten uso comercial y obra derivada (CC BY, CC BY-SA,
 * CC0, dominio público). Cada imagen se recortó y recomprimió; la atribución es
 * obligatoria y se muestra al pie de cada figura.
 *
 * Las fotografías de banco no son activos propios; ninguna imagen se usa como logotipo,
 * favicon ni imagen de marca.
 */

export interface CreditoImagen {
  titulo: string;
  autor: string;
  licencia: string;
  licenciaUrl: string;
  fuente: string;
  alt: string;
  tipo?: 'banco' | 'ia' | 'propia';
}

export const CREDITOS: Record<string, CreditoImagen> = {
  'gen-grado-entry-grade': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Un solo marco de plástico gris con pocas piezas grandes, típico de un kit de nivel inicial.",
    tipo: 'ia',
  },
  'gen-grado-high-grade': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Dos marcos de plástico gris y azul con piezas pequeñas junto a unas pinzas de corte.",
    tipo: 'ia',
  },
  'gen-grado-real-grade': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Marcos de plástico multicolor con piezas diminutas y muy densas junto a una lupa de precisión.",
    tipo: 'ia',
  },
  'gen-grado-master-grade': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Marcos de plástico apilados junto a piezas de armazón interno gris oscuro, sueltas.",
    tipo: 'ia',
  },
  'gen-grado-perfect-grade': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Gran cantidad de marcos de plástico de formato grande con piezas metalizadas, tornillos y un módulo LED.",
    tipo: 'ia',
  },
  'gen-universo-uc': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Colonia espacial cilíndrica en órbita terrestre con la Tierra al fondo.",
    tipo: 'ia',
  },
  'gen-universo-ac': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Grupo de colonias y estaciones orbitales lejanas en un punto de Lagrange, con la Tierra y la Luna.",
    tipo: 'ia',
  },
  'gen-universo-ce': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Laboratorio de biotecnología en órbita con una gran ventana hacia la Tierra.",
    tipo: 'ia',
  },
  'gen-universo-ad': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Elevador orbital que se eleva desde una plataforma oceánica al amanecer.",
    tipo: 'ia',
  },
  'gen-universo-pd': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Asentamiento industrial desgastado en la superficie de Marte con tormentas de polvo.",
    tipo: 'ia',
  },
  'gen-universo-as': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Campus corporativo moderno dentro de una estación orbital, arquitectura blanca y luminosa.",
    tipo: 'ia',
  },
  'gen-universo-cc': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Campo nocturno bajo una Luna llena enorme con ruinas antiguas cubiertas de vegetación.",
    tipo: 'ia',
  },
  'gen-art-que-es-un-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Marcos de plástico sin cortar junto a un instructivo con diagramas de piezas.",
    tipo: 'ia',
  },
  'gen-art-como-armar-tu-primer-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Manos separando una pieza de plástico del marco con pinzas de corte.",
    tipo: 'ia',
  },
  'gen-art-herramientas-para-armar-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Herramientas de modelismo ordenadas sobre un tapete de corte.",
    tipo: 'ia',
  },
  'gen-art-panel-lining-topcoat-acabados': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Rotulador de punta fina marcando líneas de panel en una pieza de plástico blanca.",
    tipo: 'ia',
  },
  'gen-art-por-que-amarillean-los-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Dos piezas de plástico idénticas: una blanca y otra amarillenta por el tiempo.",
    tipo: 'ia',
  },
  'gen-art-grados-de-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Cinco marcos de plástico ordenados de menor a mayor densidad de piezas.",
    tipo: 'ia',
  },
  'gen-art-master-grade-vs-real-grade': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Dos pilas de marcos de plástico comparadas con una regla metálica.",
    tipo: 'ia',
  },
  'gen-art-perfect-grade-que-es': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Caja grande y lisa llena de marcos de plástico empacados.",
    tipo: 'ia',
  },
  'gen-art-glosario-gunpla-terminos': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Cuaderno abierto con pluma y piezas de plástico sueltas.",
    tipo: 'ia',
  },
  'gen-art-que-significa-ver-ka': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Macro de una pieza de plástico con detalle grabado muy fino.",
    tipo: 'ia',
  },
  'gen-art-checklist-antes-de-comprar-tu-primer-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Cajas lisas de kits junto a una tabla con una lista de verificación en blanco.",
    tipo: 'ia',
  },
  'gen-art-gundam-armable-cual-comprar': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Tres cajas lisas de distinto tamaño en fila.",
    tipo: 'ia',
  },
  'gen-art-como-fotografiar-tu-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Estudio fotográfico de mesa con cámara, caja de luz y una pieza sobre base giratoria.",
    tipo: 'ia',
  },
  'gen-art-comprar-vender-gunpla-segunda-mano': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Dos personas revisan el contenido de una caja de kit sobre una mesa.",
    tipo: 'ia',
  },
  'gen-art-importar-gunpla-a-mexico': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Paquete internacional con sobre de documentos aduanales sobre un escritorio.",
    tipo: 'ia',
  },
  'gen-art-preventas-y-p-bandai-desde-mexico': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Escritorio con laptop, calendario con una fecha marcada y un paquete.",
    tipo: 'ia',
  },
  'gen-art-gunpla-fuera-de-cdmx': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Paquetes listos para envío en la trastienda de una tienda de hobby.",
    tipo: 'ia',
  },
  'gen-art-comunidad-gundam-mexico-como-unirte': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Mesa compartida donde varias personas arman modelos juntas.",
    tipo: 'ia',
  },
  'gen-art-gundam-card-game-en-mexico': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Manos de dos jugadores sobre un tapete con cartas boca abajo en un torneo.",
    tipo: 'ia',
  },
  'gen-art-videojuegos-de-gundam-que-puedes-jugar-hoy': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Manos con un control de videojuego iluminadas por la pantalla.",
    tipo: 'ia',
  },
  'gen-art-gundam-assemble-que-es': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Mesa de juego estratégico con escenografía, dados y cinta métrica.",
    tipo: 'ia',
  },
  'gen-art-requiem-for-vengeance-que-es': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Estación de trabajo de animación 3D con un paisaje renderizado en tiempo real.",
    tipo: 'ia',
  },
  'gen-art-gundam-live-action-netflix': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Cámara de cine en un set de filmación con pantalla verde.",
    tipo: 'ia',
  },
  'gen-art-cual-gundam-ver-primero': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Sala acogedora de noche iluminada por el brillo de la televisión.",
    tipo: 'ia',
  },
  'gen-ser-requiem-for-vengeance': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Pueblo europeo en ruinas cubierto de nieve al anochecer.",
    tipo: 'ia',
  },
  'gen-ms-gms-alpha-red-gundam': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Deshuesadero de colonia de noche bañado en luz roja.",
    tipo: 'ia',
  },
  'gen-ms-nz-666-kshatriya': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Interior rocoso de una base militar en un asteroide.",
    tipo: 'ia',
  },
  'gen-ms-rx-105-xi-gundam': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Tormenta eléctrica nocturna sobre un mar tropical.",
    tipo: 'ia',
  },
  'gen-ms-rx-78al-atlas-gundam': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Isla selvática del Pacífico al amanecer con vapor sobre el río.",
    tipo: 'ia',
  },
  'gen-ms-rx-78ge-gundam-ex': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Paso de montaña nevado en Europa con un puente de piedra en ruinas.",
    tipo: 'ia',
  },
  'gen-ms-x-ex01-gundam-calibarn': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Estructura orbital blanca atravesada por un solo haz de luz.",
    tipo: 'ia',
  },
  'gen-ms-xm-07-vigna-ghina': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Interior barroco aristocrático con rosas rojas dentro de una colonia.",
    tipo: 'ia',
  },
  'gen-ms-xxxg-01d-gundam-deathscythe': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Campanario de iglesia de piedra de noche bajo una luna creciente.",
    tipo: 'ia',
  },
  'gen-per-cecily-fairchild': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Mostrador de panadería familiar con pan recién hecho.",
    tipo: 'ia',
  },
  'gen-per-duo-maxwell': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Iglesia de piedra al anochecer con velas encendidas.",
    tipo: 'ia',
  },
  'gen-per-hathaway-noa': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Balcón de hotel tropical al atardecer con vista al mar.",
    tipo: 'ia',
  },
  'gen-per-marida-cruz': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Pasillo estrecho de una nave militar con una litera y luz verde.",
    tipo: 'ia',
  },
  'gen-art-cronologia-de-gundam-explicada': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Estelas de estrellas sobre un observatorio de montaña.",
    tipo: 'ia',
  },
  'gen-art-existe-lego-gundam': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Bloques de construcción genéricos junto a un marco de plástico.",
    tipo: 'ia',
  },
  'gen-art-figuras-de-gundam-vs-gunpla': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Repisa de coleccionista con una vitrina de acrílico vacía y una caja lisa.",
    tipo: 'ia',
  },
  'gen-art-gundam-build-fighters-que-es': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Mesa de competencia de modelismo bajo un reflector.",
    tipo: 'ia',
  },
  'gen-art-gundam-rogue-orbit-todo-lo-que-se-sabe': {
    titulo: 'Imagen ilustrativa generada para GUNDAMMX',
    autor: 'GUNDAMMX',
    licencia: 'Generada con IA',
    licenciaUrl: '/creditos/#imagenes-generadas',
    fuente: '/creditos/#imagenes-generadas',
    alt: "Monitor curvo con una nebulosa en una habitación oscura de videojuegos.",
    tipo: 'ia',
  },
  'art-donde-ver': {
    titulo: 'Gundam figure at Don Quijote Kaheka',
    autor: 'jdnx',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/21442511@N08/52194570136',
    alt: 'Model kit expuesto en el mostrador de una tienda de hobby.',
  },
  'art-gundam-wing': {
    titulo: 'Wing Zero Kai',
    autor: 'joo0ey',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/37238219@N00/5066980320',
    alt: 'Primer plano de un model kit del Wing Gundam Zero Kai.',
  },
  'art-historia-mexico': {
    titulo: 'GUNDAM!',
    autor: 'joo0ey',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/37238219@N00/3247856863',
    alt: 'Primer plano de un model kit del RX-78-2.',
  },
  'art-orden': {
    titulo: 'BANDAI GUNPLA',
    autor: 'othree',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/12452841@N00/9486175112',
    alt: 'Varios model kits de distintas series expuestos juntos en una vitrina.',
  },
  'art-universal-century': {
    titulo: 'RX-0 Unicorn Gundam (Unicorn Mode)',
    autor: 'Nelo Hotsuma',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/63122283@N06/44100055452',
    alt: 'Model kit del RX-0 Unicorn Gundam en modo unicornio.',
  },
  'gui-donde-comprar': {
    titulo: 'The Gundam Base Tokyo, entrance',
    autor: 'Syced',
    licencia: 'CC0 1.0',
    licenciaUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    fuente: 'https://commons.wikimedia.org/w/index.php?curid=129634893',
    alt: 'Entrada de la tienda The Gundam Base en Tokio.',
  },
  'gui-original': {
    titulo: 'BANDAI GUNPLA RG',
    autor: 'othree',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/12452841@N00/9486171428',
    alt: 'Model kit Real Grade del RX-78-2 expuesto en una vitrina.',
  },
  'gui-precio': {
    titulo: 'BANDAI GUNPLA',
    autor: 'othree',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/12452841@N00/9486179884',
    alt: 'Model kits High Grade expuestos junto a su ficha de precio.',
  },
  'hub-articulos': {
    titulo: 'Airfix Islander pieces & travelling work space, annotated, at the registration table, the day before the contest.',
    autor: 'wbaiv',
    licencia: 'CC BY-SA 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    fuente: 'https://www.flickr.com/photos/9998127@N06/4900843278',
    alt: 'Mesa de trabajo de modelismo con pinturas, piezas y herramientas.',
  },
  'hub-comunidad': {
    titulo: 'Frederic Duch 3D Model1',
    autor: 'Jefferson Lab',
    licencia: 'Dominio público (PDM 1.0)',
    licenciaUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    fuente: 'https://www.flickr.com/photos/53950384@N02/54719199815',
    alt: 'Dos personas armando un diorama a escala en una mesa de taller.',
  },
  'hub-eventos': {
    titulo: 'GUNPLA EXPO 鋼彈模型博覽會 – TAIWAN 2013',
    autor: 'othree',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/12452841@N00/9483342649',
    alt: 'Primer plano de un model kit expuesto en una exposición de Gunpla.',
  },
  'hub-guias': {
    titulo: 'Clippers, tweezers, scissors, sanding sticks',
    autor: 'wbaiv',
    licencia: 'CC BY-SA 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    fuente: 'https://www.flickr.com/photos/9998127@N06/4569806198',
    alt: 'Herramientas de modelismo sobre una mesa: pinzas, tijeras, limas, cúter y pinturas.',
  },
  'hub-gunpla': {
    titulo: 'Pull the plastic out of the bags',
    autor: 'Kaeru',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/51035756584@N01/48588655',
    alt: 'Runners de plástico de un model kit recién sacados de la bolsa, junto al instructivo.',
  },
  'hub-kits': {
    titulo: 'One or two Gundam models',
    autor: 'DocChewbacca',
    licencia: 'CC BY-SA 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    fuente: 'https://www.flickr.com/photos/49462908@N00/2871304398',
    alt: 'Estantería de tienda llena de cajas de model kits de Gunpla.',
  },
  'hub-mobile-suits': {
    titulo: 'MG MSA-0011(Ext) Ex-S Gundam',
    autor: 'Mathias Appel',
    licencia: 'CC0 1.0',
    licenciaUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    fuente: 'https://www.flickr.com/photos/91501748@N07/8566837608',
    alt: 'Model kit Master Grade del Ex-S Gundam fotografiado sobre fondo negro.',
  },
  'hub-noticias': {
    titulo: 'MG MSN-001A1 Delta Plus',
    autor: 'Mathias Appel',
    licencia: 'CC0 1.0',
    licenciaUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    fuente: 'https://www.flickr.com/photos/91501748@N07/8566832944',
    alt: 'Model kit Master Grade del Delta Plus fotografiado sobre fondo negro.',
  },
  'hub-personajes': {
    titulo: 'Singapore Gundam Model Kit Challenge 2008 - Hallelujah Rescue Campaign',
    autor: 'animaster',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/19043905@N06/3037571181',
    alt: 'Diorama con dos model kits en una escena de combate sobre ruinas.',
  },
  'hub-series': {
    titulo: 'BANDAI GUNPLA HG',
    autor: 'othree',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/12452841@N00/9486180634',
    alt: 'Vitrina con varios model kits de la línea High Grade expuestos.',
  },
  'hub-tiendas': {
    titulo: 'Gundam Model Kit Challenge - Takashimaya Singapore',
    autor: 'animaster',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/19043905@N06/3045931836',
    alt: 'Interior de una tienda de hobby con vitrinas de model kits.',
  },
  'hub-universos': {
    titulo: 'Causeway Bay Gundam EXPO Event',
    autor: 'Marco Hazard',
    licencia: 'CC BY-SA 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    fuente: 'https://www.flickr.com/photos/42405591@N02/20817729638',
    alt: 'Estatua a escala real del RX-0 Unicorn Gundam instalada en la vía pública.',
  },
  'ms-exia': {
    titulo: 'GUNDAM EXIA (REAL GRADE KIT)',
    autor: 'fotowesley',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/48923585@N06/14238127994',
    alt: 'Model kit Real Grade del GN-001 Gundam Exia.',
  },
  'ms-nu': {
    titulo: 'Nu Gundam',
    autor: 'tsuihin - TimoStudios',
    licencia: 'CC BY-SA 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    fuente: 'https://www.flickr.com/photos/19136074@N06/3118122178',
    alt: 'Model kit del RX-93 Nu Gundam armado.',
  },
  'ms-sazabi': {
    titulo: 'Sazabi',
    autor: 'othree',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/12452841@N00/14981199119',
    alt: 'Model kit del MSN-04 Sazabi armado.',
  },
  'ms-wing': {
    titulo: 'Wing GUNDAM',
    autor: 'othree',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/12452841@N00/14981296288',
    alt: 'Model kit del XXXG-01W Wing Gundam armado.',
  },
  'ms-zaku-ii': {
    titulo: 'MS-06S Zaku II',
    autor: 'JohnWCoke',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/86371376@N05/7912612886',
    alt: 'Model kit del MS-06S Zaku II armado.',
  },
  'ms-zeta': {
    titulo: 'Zeta Elevates',
    autor: 'JohnWCoke',
    licencia: 'CC BY 2.0',
    licenciaUrl: 'https://creativecommons.org/licenses/by/2.0/',
    fuente: 'https://www.flickr.com/photos/86371376@N05/8001402471',
    alt: 'Model kit del MSZ-006 Zeta Gundam armado.',
  },
  'cc-ms-asw-g-08-gundam-barbatos': {
    titulo: "HG 1/144 Gundam Barbatos (IRON BLOODED ORPHANS)",
    autor: "Marco Hazard",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/42405591@N02/24796491135",
    alt: "Model kit HG del Gundam Barbatos.",
  },
  'cc-ms-asw-g-08-gundam-barbatos-lupus-rex': {
    titulo: "Gundam Barbatos HG 1/144 (IRON BLOODED ORPHANS )",
    autor: "Marco Hazard",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/42405591@N02/24702995701",
    alt: "Model kit del Gundam Barbatos, la unidad que evoluciona hasta el Lupus Rex.",
  },
  'cc-ms-f91-gundam-f91': {
    titulo: "Anime Expo 2013 - Gundam F91",
    autor: "W10002",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/28277470@N05/9225643695",
    alt: "Gundam F91 exhibido en Anime Expo 2013.",
  },
  'cc-ms-gn-002-gundam-dynames': {
    titulo: "GUNDAM DYNAMES",
    autor: "cinz",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/29002012@N00/3014892376",
    alt: "Model kit del Gundam Dynames con su rifle de francotirador.",
  },
  'cc-ms-gn-003-gundam-kyrios': {
    titulo: "1/100 Gundam Kyrios",
    autor: "mechnine",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/45582840@N05/5066962693",
    alt: "Detalle de un model kit del Gundam Kyrios.",
  },
  'cc-ms-gn-005-gundam-virtue': {
    titulo: "Gundam Virtue",
    autor: "yonghokim",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/33793692@N00/5298647808",
    alt: "Model kit del Gundam Virtue.",
  },
  'cc-ms-mbf-p02-gundam-astray-red-frame': {
    titulo: "Astray Red Frame Kai",
    autor: "Polycaps",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/54132475@N02/5450015677",
    alt: "Model kit del Gundam Astray Red Frame con su katana.",
  },
  'cc-ms-mighty-strike-freedom-gundam': {
    titulo: "Strike Freedom Gundam Ver.∞",
    autor: "Yuichiro Haga",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/77324941@N00/2131258767",
    alt: "Model kit del Strike Freedom Gundam, la unidad de la que deriva el Mighty Strike Freedom.",
  },
  'cc-ms-mrx-009-psycho-gundam': {
    titulo: "PSYCO GUNDAM",
    autor: "Yuichiro Haga",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/77324941@N00/7038586997",
    alt: "Figura del Psycho Gundam.",
  },
  'cc-per-four-murasame': {
    titulo: "PSYCO GUNDAM",
    autor: "Yuichiro Haga",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/77324941@N00/7038586997",
    alt: "Figura del Psycho Gundam, la unidad de Four Murasame.",
  },
  'cc-ms-ms-06rb-zaku-ii-solari': {
    titulo: "MS-06 ZAKU II Realtype Color",
    autor: "JOE WU",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/34186984@N00/2332629867",
    alt: "Model kit de un Zaku II, la línea de la que deriva esta unidad.",
  },
  'cc-ms-oz-13ms-gundam-epyon': {
    titulo: "OZ-13MS Gundam Epyon Anazasi Custom",
    autor: "Anazasi Custom",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/93873152@N03/46520704301",
    alt: "Model kit del Gundam Epyon con acabado personalizado.",
  },
  'cc-ms-rx-104ff-penelope': {
    titulo: "Hathaway’s Flash: HGUC Penelope display at Gundam Base Tokyo",
    autor: "debris2019",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/143527711@N03/48215917821",
    alt: "Model kit HGUC del Penelope exhibido en The Gundam Base Tokyo.",
  },
  'cc-ms-rx-79g-ez8': {
    titulo: "Gundam RX79(G)",
    autor: "yhy_jp",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/123607272@N06/14272162240",
    alt: "Gundam Ground Type RX-79(G), la unidad que Shiro Amada reconstruye como Ez-8.",
  },
  'cc-ms-system-a99-turn-a-gundam': {
    titulo: "HG 1/144 Turn A Gundam",
    autor: "matsuyuki",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/12173213@N00/15689209339",
    alt: "Model kit del ∀ Gundam.",
  },
  'cc-ms-xvx-016-gundam-aerial': {
    titulo: "The Witch from Mercury",
    autor: "Lainax",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/60647952@N04/52912632203",
    alt: "Model kit del Gundam Aerial exhibido en una muestra de The Witch from Mercury.",
  },
  'cc-ms-xxxg-00w0-wing-gundam-zero': {
    titulo: "My 1/60 PG Wing Gundam Zero Custom",
    autor: "Fernando Marcelino",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/13651330@N04/6522092089",
    alt: "Model kit Perfect Grade del Wing Gundam Zero, versión Endless Waltz.",
  },
  'cc-ms-zgmf-x10a-freedom-gundam': {
    titulo: "Freedom Gundam statue in Shanghai",
    autor: "Conniecc120121",
    licencia: "CC BY 4.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/4.0/",
    fuente: "https://commons.wikimedia.org/wiki/File:Freedom_Gundam_statue_in_Shanghai.jpg",
    alt: "Estatua a escala del Freedom Gundam en Shanghái.",
  },
  'cc-ms-zgmf-x20a-strike-freedom-gundam': {
    titulo: "Strike Freedom Gundam Ver.∞",
    autor: "Yuichiro Haga",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/77324941@N00/2131258767",
    alt: "Model kit del Strike Freedom Gundam en exhibición.",
  },
  'cc-ms-zgmf-x42s-destiny-gundam': {
    titulo: "Metal Robot Tamashii ZGMF-X42S Destiny Gundam",
    autor: "debris2019",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/143527711@N03/46491732442",
    alt: "Figura Metal Robot Tamashii del Destiny Gundam.",
  },
  'cc-ser-08th-ms-team': {
    titulo: "Gundam RX79(G)",
    autor: "yhy_jp",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/123607272@N06/14272162240",
    alt: "Gundam Ground Type RX-79(G), unidad protagonista de The 08th MS Team.",
  },
  'cc-ser-gundam-f91': {
    titulo: "Anime Expo 2013 - Gundam F91",
    autor: "W10002",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/28277470@N05/9225643695",
    alt: "Gundam F91, protagonista de la película, exhibido en Anime Expo 2013.",
  },
  'cc-ser-gundam-seed-destiny': {
    titulo: "Metal Robot Tamashii ZGMF-X42S Destiny Gundam",
    autor: "debris2019",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/143527711@N03/46491732442",
    alt: "Figura del Destiny Gundam, protagonista de SEED Destiny.",
  },
  'cc-ser-gundam-seed-freedom': {
    titulo: "Strike Freedom Gundam Ver.∞",
    autor: "Yuichiro Haga",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/77324941@N00/2131221101",
    alt: "Detalle de un model kit del Strike Freedom Gundam, unidad central de SEED Freedom.",
  },
  'cc-ser-iron-blooded-orphans': {
    titulo: "Gundam Barbatos HG 1/144 (IRON BLOODED ORPHANS )",
    autor: "Marco Hazard",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/42405591@N02/24702995701",
    alt: "Model kit del Gundam Barbatos, protagonista de Iron-Blooded Orphans.",
  },
  'cc-ser-mobile-suit-gundam-hathaway': {
    titulo: "Hathaway’s Flash: HGUC Penelope display at Gundam Base Tokyo",
    autor: "debris2019",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/143527711@N03/48215962402",
    alt: "Model kit del Penelope, de Gundam Hathaway, en The Gundam Base Tokyo.",
  },
  'cc-ser-mobile-suit-gundam-thunderbolt': {
    titulo: "HG 1/144 FA-78 Full Armor Gundam Thunderbolt ver.",
    autor: "matsuyuki",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/12173213@N00/11927521183",
    alt: "Model kit HG del Full Armor Gundam de Gundam Thunderbolt.",
  },
  'cc-ser-the-witch-from-mercury': {
    titulo: "The Witch from Mercury",
    autor: "Lainax",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/60647952@N04/52912559080",
    alt: "Model kit del Gundam Aerial, protagonista de The Witch from Mercury.",
  },
  'cc-ser-turn-a-gundam': {
    titulo: "HG 1/144 Turn A Gundam",
    autor: "matsuyuki",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/12173213@N00/15687900810",
    alt: "Model kit del ∀ Gundam.",
  },
  'cc-per-allelujah-haptism': {
    titulo: "Arios Gundam",
    autor: "tsuihin - TimoStudios",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/19136074@N06/3816104345",
    alt: "Model kit del Arios Gundam, unidad de Allelujah Haptism.",
  },
  'cc-per-amuro-ray': {
    titulo: "DiverCity Tokyo Plaza: RG1/1 RX-78-2 Gundam Ver.GFT",
    autor: "Dick Thomas Johnson",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/31029865@N06/16476521573",
    alt: "Estatua a escala real del RX-78-2 Gundam, la unidad de Amuro Ray.",
  },
  'cc-per-banagher-links': {
    titulo: "RX-0 Unicorn Gundam (Destroy Mode)",
    autor: "Nelo Hotsuma",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/63122283@N06/44101134712",
    alt: "Estatua del Unicorn Gundam, la unidad de Banagher Links.",
  },
  'cc-per-char-aznable': {
    titulo: "HGUC ν Gundam & HGUC Sazabi",
    autor: "FHKE",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/16226024@N00/2671889764",
    alt: "Model kits del ν Gundam y del Sazabi, la unidad de Char en Char's Counterattack.",
  },
  'cc-per-heero-yuy': {
    titulo: "My 1/60 PG Wing Gundam Zero Custom",
    autor: "Fernando Marcelino",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/13651330@N04/6522095587",
    alt: "Model kit Perfect Grade del Wing Gundam Zero, la unidad de Heero Yuy.",
  },
  'cc-per-io-fleming': {
    titulo: "HG 1/144 FA-78 Full Armor Gundam Thunderbolt ver.",
    autor: "matsuyuki",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/12173213@N00/11927253455",
    alt: "Model kit del Full Armor Gundam de Thunderbolt, la unidad de Io Fleming.",
  },
  'cc-per-iria-solari': {
    titulo: "MS-06 ZAKU II First Mass production",
    autor: "JOE WU",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/34186984@N00/2332630385",
    alt: "Model kit de un Zaku II, la línea de la unidad de Iria Solari.",
  },
  'cc-per-kamille-bidan': {
    titulo: "msz-006 Zeta Gundam",
    autor: "cosmos28",
    licencia: "CC BY 4.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/4.0/",
    fuente: "https://sketchfab.com/3d-models/c79a648bdd1b4ccfbf11f2dc5f836a66",
    alt: "Model kit del Zeta Gundam, la unidad de Kamille Bidan.",
  },
  'cc-per-kira-yamato': {
    titulo: "Strike Freedom Gundam Ver.∞",
    autor: "Yuichiro Haga",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/77324941@N00/2131258641",
    alt: "Model kit del Strike Freedom Gundam, la unidad de Kira Yamato.",
  },
  'cc-per-lacus-clyne': {
    titulo: "Strike Freedom Gundam Ver.∞",
    autor: "Yuichiro Haga",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/77324941@N00/2132035488",
    alt: "Model kit del Strike Freedom Gundam, la unidad que Lacus Clyne entrega a Kira.",
  },
  'cc-per-lockon-stratos': {
    titulo: "Gundam Dynames.",
    autor: "The Magic Tuba Pixie",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/34017082@N06/4275025527",
    alt: "Model kit del Gundam Dynames, la unidad de Lockon Stratos.",
  },
  'cc-per-loran-cehack': {
    titulo: "HG 1/144 Turn A Gundam",
    autor: "matsuyuki",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/12173213@N00/14504412755",
    alt: "Detalle de un model kit del ∀ Gundam, la unidad de Loran Cehack.",
  },
  'cc-per-lowe-guele': {
    titulo: "My current work #coffeebreak #gunpla. #realgrade #Gundam Astray Red Frame. Finished the legs & waist today. Super solid build thus far.",
    autor: "dion [oʇoɥdʞoɯɐ]",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/79428643@N00/21753675163",
    alt: "Model kit del Gundam Astray Red Frame, la unidad de Lowe Guele.",
  },
  'cc-per-mikazuki-augus': {
    titulo: "HG 1/144 Gundam Barbatos (IRON BLOODED ORPHANS)",
    autor: "Marco Hazard",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/42405591@N02/24796490285",
    alt: "Model kit del Gundam Barbatos, la unidad de Mikazuki Augus.",
  },
  'cc-per-seabook-arno': {
    titulo: "Snap-fit vs first pass of detailing on the head & chest skull. MG Gundam Crossbones X3. #pbandai #plamo #gunpla #bandai #mastergrade #modelkits",
    autor: "dion [oʇoɥdʞoɯɐ]",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/79428643@N00/25475128531",
    alt: "Detalle del pecho de un model kit del Crossbone Gundam, unidad posterior de Seabook Arno.",
  },
  'cc-per-setsuna-f-seiei': {
    titulo: "GUNDAM EXIA (REAL GRADE KIT))",
    autor: "fotowesley",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/48923585@N06/14051800300",
    alt: "Model kit del Gundam Exia, la unidad de Setsuna F. Seiei.",
  },
  'cc-per-shinn-asuka': {
    titulo: "MG Sword Impulse",
    autor: "Polycaps",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/54132475@N02/6062871125",
    alt: "Model kit del Sword Impulse Gundam, la unidad de Shinn Asuka.",
  },
  'cc-per-shiro-amada': {
    titulo: "Gundam RX79(G)",
    autor: "yhy_jp",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/123607272@N06/14272162240",
    alt: "Gundam Ground Type RX-79(G), la unidad de Shiro Amada.",
  },
  'cc-per-suletta-mercury': {
    titulo: "The Witch from Mercury",
    autor: "Lainax",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/60647952@N04/52912559080",
    alt: "Model kit del Gundam Aerial, la unidad de Suletta Mercury.",
  },
  'cc-per-tieria-erde': {
    titulo: "Gundam Virtue",
    autor: "yonghokim",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/33793692@N00/5298647808",
    alt: "Model kit del Gundam Virtue, la unidad de Tieria Erde.",
  },
  'cc-art-char-aznable-quien-es': {
    titulo: "HGUC ν Gundam & HGUC Sazabi",
    autor: "FHKE",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/16226024@N00/2671889764",
    alt: "Model kits del ν Gundam y del Sazabi, la unidad de Char en Char's Counterattack.",
  },
  'cc-art-el-zaku-por-que-importa': {
    titulo: "MS-06S ZAKU II(HCM-Pro Version)",
    autor: "JOE WU",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/34186984@N00/2333457984",
    alt: "Figura del Zaku II de Char en un hangar a escala.",
  },
  'cc-art-en-que-orden-ver-gundam-wing': {
    titulo: "Gundam Wing Zero",
    autor: "RSLab",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/134584268@N04/33018501065",
    alt: "Model kit del Wing Gundam Zero de Endless Waltz.",
  },
  'cc-art-gundam-escala-real-yokohama-odaiba': {
    titulo: "GUNDAM FACTORY YOKOHAMA",
    autor: "Dick Thomas Johnson",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/31029865@N06/54198020229",
    alt: "El RX-78F00 a escala real en Gundam Factory Yokohama.",
  },
  'cc-art-gundam-hathaway-2-sorcery-of-nymph-circe': {
    titulo: "Hathaway’s Flash: HGUC Penelope display at Gundam Base Tokyo",
    autor: "debris2019",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/143527711@N03/48215962342",
    alt: "Model kit del Penelope, de Gundam Hathaway, en exhibición.",
  },
  'cc-art-gundam-seed-guia-y-orden': {
    titulo: "Strike Freedom Gundam Ver.∞",
    autor: "Yuichiro Haga",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/77324941@N00/2131258641",
    alt: "Model kit del Strike Freedom Gundam, de la saga SEED.",
  },
  'cc-art-gundam-unicorn-guia': {
    titulo: "RX-0 Unicorn Gundam (Destroy Mode)",
    autor: "Nelo Hotsuma",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/63122283@N06/30282496498",
    alt: "Estatua del Unicorn Gundam en DiverCity Tokyo Plaza, de noche.",
  },
  'cc-art-pilotos-de-gundam-wing': {
    titulo: "Gundam Wing custom",
    autor: "nabuhunso",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/11061029@N04/22618072829",
    alt: "Model kit personalizado del Wing Gundam Zero.",
  },
  'cc-art-que-es-gundam': {
    titulo: "DiverCity Tokyo Plaza: RG1/1 RX-78-2 Gundam Ver.GFT",
    autor: "Dick Thomas Johnson",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/31029865@N06/16476519473",
    alt: "Estatua a escala real del RX-78-2 Gundam en Odaiba.",
  },
  'cc-art-que-significa-gundam': {
    titulo: "DiverCity Tokyo Plaza: RG1/1 RX-78-2 Gundam Ver.GFT",
    autor: "Dick Thomas Johnson",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/31029865@N06/16476521573",
    alt: "Estatua a escala real del RX-78-2, el primer Gundam.",
  },
  'cc-art-the-gundam-base-mexico': {
    titulo: "GUNDAM BASE TAIPEI-GBT",
    autor: "JerryLai0208",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/51449066@N06/4963341378",
    alt: "Exhibición de model kits en The Gundam Base Taipei.",
  },
  'cc-art-witch-from-mercury-guia': {
    titulo: "The Witch from Mercury",
    autor: "Lainax",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/60647952@N04/52912632203",
    alt: "Model kit del Gundam Aerial en una muestra de The Witch from Mercury.",
  },
  'cc-art-zeta-gundam-guia': {
    titulo: "Zeta Gundam and HYAKUSHIKI",
    autor: "Le Ciel Azuré",
    licencia: "CC BY-SA 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    fuente: "https://www.flickr.com/photos/12057629@N04/3458851125",
    alt: "Figuras del Zeta Gundam y del Hyaku Shiki en exhibición.",
  },
  'cc-art-eventos-gundam-mexico': {
    titulo: "GUNPLA EXPO 鋼彈模型博覽會 – TAIWAN 2013",
    autor: "othree",
    licencia: "CC BY 2.0",
    licenciaUrl: "https://creativecommons.org/licenses/by/2.0/",
    fuente: "https://www.flickr.com/photos/12452841@N00/9486169242",
    alt: "Modelista armando Gunpla en la Gunpla Expo Taiwán 2013.",
  },
  'un-gquuuuuux': {
    titulo: 'A futuristic robot with a weapon is posed',
    autor: 'Ash-Lab',
    licencia: 'Licencia Unsplash',
    licenciaUrl: 'https://unsplash.com/license',
    fuente: 'https://unsplash.com/photos/f8RRflQZmOY',
    alt: 'Model kit HG del GQuuuuuuX con su rifle.',
  },
  'un-strike-gundam': {
    titulo: 'A futuristic robot stands against a blur of colorful lights',
    autor: 'Sulhan Aldani',
    licencia: 'Licencia Unsplash',
    licenciaUrl: 'https://unsplash.com/license',
    fuente: 'https://unsplash.com/photos/-9_d7__KSnc',
    alt: 'Model kit del Strike Gundam frente a estelas de luz.',
  },
};
